# Generated by Django 3.2.6 on 2021-09-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_id',
            fields=[
                ('course_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('course_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sign_up',
            fields=[
                ('id', models.CharField(max_length=50)),
                ('name', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('mobile_no', models.IntegerField()),
                ('institute_name', models.TextField()),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.role_id')),
            ],
        ),
        migrations.CreateModel(
            name='exam_details',
            fields=[
                ('exam_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('exam_title', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('no_of_ques', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.course_id')),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.sign_up')),
            ],
        ),
        migrations.CreateModel(
            name='courses_availed',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.course_id')),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.sign_up')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.role_id')),
            ],
        ),
        migrations.CreateModel(
            name='class_stu_tech',
            fields=[
                ('class_stu_tech', models.IntegerField()),
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.sign_up')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.role_id')),
            ],
        ),
    ]
