# Generated by Django 3.2.6 on 2021-09-02 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_class_stu_tech_course_id_courses_availed_exam_details_sign_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign_up',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
